=== rmelick/hanabi-live-bot/src/main/java/net/rmelick/hanabi/bot/live/connector/schemas/jsonschema/table.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Table",
  "definitions": {
    "Table": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "password": {
          "type": "boolean"
        },
        "joined": {
          "type": "boolean"
        },
        "numPlayers": {
          "type": "integer"
        },
        "owned": {
          "type": "boolean"
        },
        "running": {
          "type": "boolean"
        },
        "variant": {
          "type": "string"
        },
        "timed": {
          "type": "boolean"
        },
        "baseTime": {
          "type": "integer"
        },
        "timePerTurn": {
          "type": "integer"
        },
        "sharedReplay": {
          "type": "boolean"
        },
        "progress": {
          "type": "integer"
        },
        "players": {
          "type": "string"
        },
        "spectators": {
          "type": "string"
        }
      },
      "required": [
        "baseTime",
        "id",
        "joined",
        "name",
        "numPlayers",
        "owned",
        "password",
        "players",
        "progress",
        "running",
        "sharedReplay",
        "spectators",
        "timePerTurn",
        "timed",
        "variant"
      ],
      "title": "Table"
    }
  }
}

=== rmelick/hanabi-live-bot/src/main/java/net/rmelick/hanabi/live/bot/application/schemas/json/table.json
{
  "id": 4212,
  "name": "Shared replay for game #106849",
  "password": false,
  "joined": false,
  "numPlayers": 3,
  "owned": false,
  "running": true,
  "variant": "Black (6 Suits)",
  "timed": false,
  "baseTime": 0,
  "timePerTurn": 0,
  "sharedReplay": true,
  "progress": 100,
  "players": "jbthea, cheikes, jonnydee",
  "spectators": "jbthea, cheikes, jonnydee"
}
